#!/bin/sh
python createdb.py
python mezzanineapp/manage.py syncdb --noinput
mkdir -p /home/dotcloud/data/media
ln -sf /home/dotcloud/current/static /home/dotcloud/static
python mezzanineapp/manage.py collectstatic --noinput
